// OTOMATIK URETILDI — demo verisi. Gorsellerin tamami temsilidir.
import { Emlakci, Ilan } from "./tipler";

export const EMLAKCILAR: Emlakci[] = [
  { slug: "yeliz-akinci", ad: "Yeliz Akıncı", firma: "Kıbrıs Kıyı Emlak", kidemYil: 8, telefon: "+90 533 853 00 80", whatsapp: "905338530080", ruhsatNo: "KKTC-EM-2018-0431", ruhsatDogrulandi: true },
  { slug: "mert-ozan", ad: "Mert Ozan", firma: "Bellapais Property", kidemYil: 5, telefon: "+90 542 871 22 14", whatsapp: "905428712214", ruhsatNo: "KKTC-EM-2021-0912", ruhsatDogrulandi: true },
  { slug: "deniz-tuncel", ad: "Deniz Tuncel", firma: "Levant Estates", kidemYil: 11, telefon: "+90 548 330 45 09", whatsapp: "905483304509", ruhsatNo: "KKTC-EM-2015-0117", ruhsatDogrulandi: true },
  { slug: "ayse-kurtulus", ad: "Ayşe Kurtuluş", firma: "Long Beach Yatırım", kidemYil: 3, telefon: "+90 533 442 77 65", whatsapp: "905334427765", ruhsatNo: "KKTC-EM-2023-1284", ruhsatDogrulandi: false },
  { slug: "kemal-arda", ad: "Kemal Arda", firma: "Arda İnşaat", kidemYil: 16, telefon: "+90 542 209 61 30", whatsapp: "905422096130", ruhsatNo: "KKTC-IN-2010-0044", ruhsatDogrulandi: true },
];

export const ILANLAR: Ilan[] = [
  {
    id: 101, slug: "girne-merkez-deniz-manzarali-rezidans",
    baslik: { tr: "Girne merkezde deniz manzaralı 2+1 rezidans", en: "Sea view 2+1 residence in Kyrenia centre", ru: "Резиденция 2+1 с видом на море в центре Кирении" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "rezidans", fiyat: 285000,
    sehir: "Girne", bolge: "Girne Merkez",
    oda: "2+1", banyo: 2, m2: 125, binaYasi: 1,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 130,
    ozellikler: ["Asansör", "Kapalı otopark", "Ortak havuz", "Jeneratör", "Çelik kapı", "Deniz manzarası", "Şehir içi"],
    kapak: "/gorsel/ilan/ilan-06.webp",
    gorseller: ["/gorsel/ilan/ilan-06.webp", "/gorsel/ilan/ilan-15.webp", "/gorsel/ilan/ilan-11.webp", "/gorsel/oda/oda-01.webp"],
    emlakci: "yeliz-akinci",
    yayinTarihi: "2026-02-11", guncelleme: "2026-09-11",
    goruntulenme: 457,
    vitrin: true,
    aiOdaGorseli: "/gorsel/oda/oda-01.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-01__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-01__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-01__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-01__modern-luks.webp" }
    ],
    konum: { lat: 35.3416, lng: 33.3192 },
  },
  {
    id: 102, slug: "alsancak-havuzlu-luks-villa",
    baslik: { tr: "Alsancak'ta özel havuzlu 4+1 lüks villa", en: "Luxury 4+1 villa with private pool in Alsancak", ru: "Роскошная вилла 4+1 с бассейном в Алсанджаке" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "villa", fiyat: 745000,
    sehir: "Girne", bolge: "Alsancak",
    oda: "4+1", banyo: 4, m2: 310, binaYasi: 2,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    
    ozellikler: ["Özel havuz", "Bahçe", "Kapalı otopark", "Jeneratör", "Şömine", "Deniz manzarası", "Güvenlik kamerası"],
    kapak: "/gorsel/ilan/ilan-07.webp",
    gorseller: ["/gorsel/ilan/ilan-07.webp", "/gorsel/ilan/ilan-05.webp", "/gorsel/ilan/ilan-08.webp", "/gorsel/oda/oda-05.webp"],
    emlakci: "deniz-tuncel",
    yayinTarihi: "2026-03-12", guncelleme: "2026-09-12",
    goruntulenme: 594,
    vitrin: true,
    aiOdaGorseli: "/gorsel/oda/oda-05.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-05__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-05__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-05__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-05__modern-luks.webp" }
    ],
    konum: { lat: 35.3389, lng: 33.2114 },
  },
  {
    id: 103, slug: "catalkoy-bahceli-bungalov",
    baslik: { tr: "Çatalköy'de bahçeli müstakil bungalov", en: "Detached bungalow with garden in Çatalköy", ru: "Отдельный бунгало с садом в Чаталкёй" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "mustakil", fiyat: 395000,
    sehir: "Girne", bolge: "Çatalköy",
    oda: "3+1", banyo: 2, m2: 180, binaYasi: 4,
    esyali: "yarı", tapu: "turk-kocani", yabanciUygun: true,
    
    ozellikler: ["Bahçe", "Barbekü", "Su kuyusu", "Otopark", "Dağ manzarası", "Güneş enerjisi"],
    kapak: "/gorsel/ilan/ilan-03.webp",
    gorseller: ["/gorsel/ilan/ilan-03.webp", "/gorsel/ilan/ilan-02.webp", "/gorsel/oda/oda-04.webp"],
    emlakci: "mert-ozan",
    yayinTarihi: "2026-04-13", guncelleme: "2026-09-13",
    goruntulenme: 731,
    
    aiOdaGorseli: "/gorsel/oda/oda-04.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-04__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-04__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-04__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-04__modern-luks.webp" }
    ],
    konum: { lat: 35.3457, lng: 33.4021 },
  },
  {
    id: 104, slug: "long-beach-yatirimlik-studyo",
    baslik: { tr: "Long Beach'te yatırımlık 1+0 stüdyo", en: "Investment studio in Long Beach", ru: "Студия для инвестиций в Лонг Бич" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "daire", fiyat: 96500,
    sehir: "İskele", bolge: "Long Beach",
    oda: "1+0", banyo: 1, m2: 48, binaYasi: 1,
    esyali: "esyali", tapu: "tmd", yabanciUygun: true,
    aidat: 45,
    ozellikler: ["Ortak havuz", "Asansör", "Güvenlik kamerası", "Denize sıfır", "Jeneratör"],
    kapak: "/gorsel/ilan/ilan-19.webp",
    gorseller: ["/gorsel/ilan/ilan-19.webp", "/gorsel/ilan/ilan-04.webp", "/gorsel/oda/oda-09.webp"],
    emlakci: "ayse-kurtulus",
    yayinTarihi: "2026-05-14", guncelleme: "2026-09-14",
    goruntulenme: 868,
    
    aiOdaGorseli: "/gorsel/oda/oda-09.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-09__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-09__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-09__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-09__modern-luks.webp" }
    ],
    konum: { lat: 35.3011, lng: 33.8894 },
  },
  {
    id: 105, slug: "bellapais-manzarali-tas-ev",
    baslik: { tr: "Bellapais'te manzaralı restore taş ev", en: "Restored stone house with view in Bellapais", ru: "Отреставрированный каменный дом в Беллапаисе" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "mustakil", fiyat: 520000,
    sehir: "Girne", bolge: "Bellapais",
    oda: "3+1", banyo: 3, m2: 205, binaYasi: 45,
    esyali: "esyasiz", tapu: "esdeger", yabanciUygun: false,
    
    ozellikler: ["Bahçe", "Şömine", "Teras", "Dağ manzarası", "Deniz manzarası", "Su kuyusu"],
    kapak: "/gorsel/ilan/ilan-01.webp",
    gorseller: ["/gorsel/ilan/ilan-01.webp", "/gorsel/ilan/ilan-22.webp"],
    emlakci: "deniz-tuncel",
    yayinTarihi: "2026-06-15", guncelleme: "2026-09-15",
    goruntulenme: 1005,
    
    konum: { lat: 35.3053, lng: 33.3547 },
  },
  {
    id: 106, slug: "lefkosa-dereboyu-ofis-katı",
    baslik: { tr: "Lefkoşa Dereboyu'nda komple ofis katı", en: "Whole office floor on Dereboyu, Nicosia", ru: "Целый офисный этаж на Деребою, Никосия" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "kiralik", tip: "ticari", fiyat: 1650,
    sehir: "Lefkoşa", bolge: "Dereboyu",
    oda: "6+1", banyo: 3, m2: 240, binaYasi: 7,
    esyali: "esyasiz", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 180,
    ozellikler: ["Asansör", "Jeneratör", "Kapalı otopark", "Yangın alarmı", "Şehir içi"],
    kapak: "/gorsel/ilan/ilan-17.webp",
    gorseller: ["/gorsel/ilan/ilan-17.webp", "/gorsel/ilan/ilan-16.webp", "/gorsel/oda/oda-06.webp"],
    emlakci: "kemal-arda",
    yayinTarihi: "2026-07-16", guncelleme: "2026-09-16",
    goruntulenme: 1142,
    
    aiOdaGorseli: "/gorsel/oda/oda-06.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-06__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-06__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-06__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-06__modern-luks.webp" }
    ],
    konum: { lat: 35.1856, lng: 33.3572 },
  },
  {
    id: 107, slug: "esentepe-golf-manzarali-daire",
    baslik: { tr: "Esentepe'de golf manzaralı 2+1", en: "2+1 with golf view in Esentepe", ru: "Квартира 2+1 с видом на гольф в Эсентепе" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "daire", fiyat: 168000,
    sehir: "Girne", bolge: "Esentepe",
    oda: "2+1", banyo: 2, m2: 95, binaYasi: 3,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 60,
    ozellikler: ["Ortak havuz", "Asansör", "Otopark", "Doğa manzarası", "Balkon"],
    kapak: "/gorsel/ilan/ilan-18.webp",
    gorseller: ["/gorsel/ilan/ilan-18.webp", "/gorsel/ilan/ilan-16.webp", "/gorsel/oda/oda-03.webp"],
    emlakci: "mert-ozan",
    yayinTarihi: "2026-08-17", guncelleme: "2026-09-17",
    goruntulenme: 1279,
    
    aiOdaGorseli: "/gorsel/oda/oda-03.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-03__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-03__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-03__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-03__modern-luks.webp" }
    ],
    konum: { lat: 35.3547, lng: 33.5286 },
  },
  {
    id: 108, slug: "karsiyaka-denize-sifir-villa",
    baslik: { tr: "Karşıyaka'da denize sıfır müstakil villa", en: "Beachfront detached villa in Karşıyaka", ru: "Вилла на первой линии моря в Каршияке" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "villa", fiyat: 865000,
    sehir: "Girne", bolge: "Karşıyaka",
    oda: "5+1", banyo: 4, m2: 380, binaYasi: 6,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    
    ozellikler: ["Özel havuz", "Denize sıfır", "Bahçe", "Barbekü", "Jeneratör", "Güvenlik kamerası", "Teras"],
    kapak: "/gorsel/ilan/ilan-13.webp",
    gorseller: ["/gorsel/ilan/ilan-13.webp", "/gorsel/ilan/ilan-23.webp", "/gorsel/ilan/ilan-20.webp"],
    emlakci: "deniz-tuncel",
    yayinTarihi: "2026-09-18", guncelleme: "2026-09-18",
    goruntulenme: 1416,
    vitrin: true,
    konum: { lat: 35.3428, lng: 33.0289 },
  },
  {
    id: 109, slug: "gonyeli-aile-dairesi",
    baslik: { tr: "Gönyeli'de geniş 3+1 aile dairesi", en: "Spacious 3+1 family flat in Gönyeli", ru: "Просторная квартира 3+1 в Гёньели" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "daire", fiyat: 142000,
    sehir: "Lefkoşa", bolge: "Gönyeli",
    oda: "3+1", banyo: 2, m2: 140, binaYasi: 9,
    esyali: "esyasiz", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 35,
    ozellikler: ["Asansör", "Otopark", "Balkon", "Çelik kapı", "Şehir içi"],
    kapak: "/gorsel/ilan/ilan-12.webp",
    gorseller: ["/gorsel/ilan/ilan-12.webp", "/gorsel/ilan/ilan-16.webp", "/gorsel/oda/oda-02.webp"],
    emlakci: "kemal-arda",
    yayinTarihi: "2026-01-10", guncelleme: "2026-09-10",
    goruntulenme: 1553,
    
    aiOdaGorseli: "/gorsel/oda/oda-02.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-02__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-02__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-02__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-02__modern-luks.webp" }
    ],
    konum: { lat: 35.2242, lng: 33.2894 },
  },
  {
    id: 110, slug: "lapta-zeytinlikli-arazi-evi",
    baslik: { tr: "Lapta'da zeytinlikli taş ev", en: "Stone house with olive grove in Lapta", ru: "Каменный дом с оливковой рощей в Лапте" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "mustakil", fiyat: 430000,
    sehir: "Girne", bolge: "Lapta",
    oda: "4+1", banyo: 2, m2: 230, binaYasi: 22,
    esyali: "yarı", tapu: "esdeger", yabanciUygun: false,
    
    ozellikler: ["Bahçe", "Su kuyusu", "Barbekü", "Şömine", "Deniz manzarası", "Doğa manzarası"],
    kapak: "/gorsel/ilan/ilan-21.webp",
    gorseller: ["/gorsel/ilan/ilan-21.webp", "/gorsel/ilan/ilan-22.webp"],
    emlakci: "yeliz-akinci",
    yayinTarihi: "2026-02-11", guncelleme: "2026-09-11",
    goruntulenme: 1690,
    
    konum: { lat: 35.3402, lng: 33.1503 },
  },
  {
    id: 111, slug: "girne-merkez-kiralik-esyali",
    baslik: { tr: "Girne merkezde eşyalı 2+1 kiralık", en: "Furnished 2+1 to rent in Kyrenia centre", ru: "Меблированная 2+1 в аренду в центре Кирении" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "kiralik", tip: "daire", fiyat: 850,
    sehir: "Girne", bolge: "Girne Merkez",
    oda: "2+1", banyo: 2, m2: 105, binaYasi: 5,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 55,
    ozellikler: ["Asansör", "Otopark", "Balkon", "Jeneratör", "Şehir içi"],
    kapak: "/gorsel/ilan/ilan-15.webp",
    gorseller: ["/gorsel/ilan/ilan-15.webp", "/gorsel/ilan/ilan-17.webp", "/gorsel/oda/oda-08.webp"],
    emlakci: "yeliz-akinci",
    yayinTarihi: "2026-03-12", guncelleme: "2026-09-12",
    goruntulenme: 1827,
    
    aiOdaGorseli: "/gorsel/oda/oda-08.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-08__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-08__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-08__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-08__modern-luks.webp" }
    ],
    konum: { lat: 35.3402, lng: 33.3186 },
  },
  {
    id: 112, slug: "bogaz-marina-manzarali-penthouse",
    baslik: { tr: "Boğaz'da marina manzaralı penthouse", en: "Marina view penthouse in Boğaz", ru: "Пентхаус с видом на марину в Богазе" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "rezidans", fiyat: 395000,
    sehir: "İskele", bolge: "Boğaz",
    oda: "3+1", banyo: 3, m2: 175, binaYasi: 2,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 95,
    ozellikler: ["Asansör", "Ortak havuz", "Teras", "Deniz manzarası", "Jeneratör", "Kapalı otopark"],
    kapak: "/gorsel/ilan/ilan-23.webp",
    gorseller: ["/gorsel/ilan/ilan-23.webp", "/gorsel/ilan/ilan-11.webp", "/gorsel/oda/oda-07.webp"],
    emlakci: "ayse-kurtulus",
    yayinTarihi: "2026-04-13", guncelleme: "2026-09-13",
    goruntulenme: 1964,
    vitrin: true,
    aiOdaGorseli: "/gorsel/oda/oda-07.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-07__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-07__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-07__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-07__modern-luks.webp" }
    ],
    konum: { lat: 35.2861, lng: 33.8103 },
  },
  {
    id: 113, slug: "ozankoy-bahceli-ikiz-villa",
    baslik: { tr: "Ozanköy'de bahçeli ikiz villa", en: "Semi-detached villa with garden in Ozanköy", ru: "Дуплекс-вилла с садом в Озанкёй" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "villa", fiyat: 298000,
    sehir: "Girne", bolge: "Ozanköy",
    oda: "3+1", banyo: 3, m2: 165, binaYasi: 3,
    esyali: "esyasiz", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 70,
    ozellikler: ["Ortak havuz", "Bahçe", "Otopark", "Dağ manzarası", "Barbekü"],
    kapak: "/gorsel/ilan/ilan-14.webp",
    gorseller: ["/gorsel/ilan/ilan-14.webp", "/gorsel/ilan/ilan-08.webp", "/gorsel/oda/oda-10.webp"],
    emlakci: "mert-ozan",
    yayinTarihi: "2026-05-14", guncelleme: "2026-09-14",
    goruntulenme: 2101,
    
    aiOdaGorseli: "/gorsel/oda/oda-10.webp",
    aiTasarimlar: [
      { stil: "akdeniz", ad: { tr: "Akdeniz", en: "Mediterranean", ru: "Средиземноморский" }, gorsel: "/gorsel/ai/oda-10__akdeniz.webp" },
      { stil: "modern-minimal", ad: { tr: "Modern Minimal", en: "Modern Minimal", ru: "Модерн-минимализм" }, gorsel: "/gorsel/ai/oda-10__modern-minimal.webp" },
      { stil: "iskandinav", ad: { tr: "İskandinav", en: "Scandinavian", ru: "Скандинавский" }, gorsel: "/gorsel/ai/oda-10__iskandinav.webp" },
      { stil: "modern-luks", ad: { tr: "Modern Lüks", en: "Modern Luxury", ru: "Современная роскошь" }, gorsel: "/gorsel/ai/oda-10__modern-luks.webp" }
    ],
    konum: { lat: 35.3231, lng: 33.3428 },
  },
  {
    id: 114, slug: "tuzla-modern-daire",
    baslik: { tr: "Gazimağusa Tuzla'da modern 2+1", en: "Modern 2+1 in Tuzla, Famagusta", ru: "Современная 2+1 в Тузле, Фамагуста" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "daire", fiyat: 118000,
    sehir: "Gazimağusa", bolge: "Tuzla",
    oda: "2+1", banyo: 1, m2: 88, binaYasi: 1,
    esyali: "esyasiz", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 40,
    ozellikler: ["Asansör", "Otopark", "Balkon", "Güneş enerjisi"],
    kapak: "/gorsel/ilan/ilan-16.webp",
    gorseller: ["/gorsel/ilan/ilan-16.webp", "/gorsel/ilan/ilan-18.webp"],
    emlakci: "kemal-arda",
    yayinTarihi: "2026-06-15", guncelleme: "2026-09-15",
    goruntulenme: 2238,
    
    konum: { lat: 35.1089, lng: 33.9403 },
  },
  {
    id: 115, slug: "edremit-havuzlu-kiralik-villa",
    baslik: { tr: "Edremit'te havuzlu kiralık villa", en: "Villa with pool to rent in Edremit", ru: "Вилла с бассейном в аренду в Эдремите" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "kiralik", tip: "villa", fiyat: 1450,
    sehir: "Girne", bolge: "Edremit",
    oda: "4+1", banyo: 3, m2: 260, binaYasi: 8,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    
    ozellikler: ["Özel havuz", "Bahçe", "Barbekü", "Jeneratör", "Deniz manzarası", "Güvenlik kamerası"],
    kapak: "/gorsel/ilan/ilan-08.webp",
    gorseller: ["/gorsel/ilan/ilan-08.webp", "/gorsel/ilan/ilan-05.webp"],
    emlakci: "deniz-tuncel",
    yayinTarihi: "2026-07-16", guncelleme: "2026-09-16",
    goruntulenme: 2375,
    
    konum: { lat: 35.3319, lng: 33.2786 },
  },
  {
    id: 116, slug: "yenikent-yatirimlik-daire",
    baslik: { tr: "Yenikent'te kiracılı yatırımlık daire", en: "Tenanted investment flat in Yenikent", ru: "Инвестиционная квартира с арендатором" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "daire", fiyat: 86000,
    sehir: "Lefkoşa", bolge: "Yenikent",
    oda: "2+1", banyo: 1, m2: 80, binaYasi: 12,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 25,
    ozellikler: ["Otopark", "Balkon", "Çelik kapı"],
    kapak: "/gorsel/ilan/ilan-09.webp",
    gorseller: ["/gorsel/ilan/ilan-09.webp", "/gorsel/ilan/ilan-17.webp"],
    emlakci: "kemal-arda",
    yayinTarihi: "2026-08-17", guncelleme: "2026-09-17",
    goruntulenme: 2512,
    
    konum: { lat: 35.2189, lng: 33.2712 },
  },
  {
    id: 117, slug: "arapkoy-panoramik-arsa",
    baslik: { tr: "Arapköy'de panoramik manzaralı imarlı arsa", en: "Panoramic building plot in Arapköy", ru: "Участок с панорамным видом в Арапкёй" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "arsa", fiyat: 215000,
    sehir: "Girne", bolge: "Arapköy",
    oda: "—", banyo: 0, m2: 1340, binaYasi: 0,
    esyali: "esyasiz", tapu: "turk-kocani", yabanciUygun: true,
    
    ozellikler: ["Yol", "Elektrik altyapısı", "Su altyapısı", "Deniz manzarası", "Dağ manzarası"],
    kapak: "/gorsel/ilan/ilan-20.webp",
    gorseller: ["/gorsel/ilan/ilan-20.webp", "/gorsel/ilan/ilan-01.webp"],
    emlakci: "yeliz-akinci",
    yayinTarihi: "2026-09-18", guncelleme: "2026-09-18",
    goruntulenme: 2649,
    
    konum: { lat: 35.3372, lng: 33.4356 },
  },
  {
    id: 118, slug: "sakarya-ogrenci-daire",
    baslik: { tr: "Gazimağusa Sakarya'da kiralık öğrenci dairesi", en: "Student flat to rent in Sakarya, Famagusta", ru: "Студенческая квартира в аренду, Фамагуста" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "kiralik", tip: "daire", fiyat: 520,
    sehir: "Gazimağusa", bolge: "Sakarya",
    oda: "1+1", banyo: 1, m2: 55, binaYasi: 6,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 30,
    ozellikler: ["Asansör", "Balkon", "Şehir içi"],
    kapak: "/gorsel/ilan/ilan-10.webp",
    gorseller: ["/gorsel/ilan/ilan-10.webp", "/gorsel/ilan/ilan-19.webp"],
    emlakci: "ayse-kurtulus",
    yayinTarihi: "2026-01-10", guncelleme: "2026-09-10",
    goruntulenme: 386,
    
    konum: { lat: 35.1345, lng: 33.9078 },
  },
  {
    id: 119, slug: "zeytinlik-turk-kocanli-villa",
    baslik: { tr: "Zeytinlik'te Türk koçanlı 4+1 villa", en: "4+1 villa with Turkish title in Zeytinlik", ru: "Вилла 4+1 с турецким титулом в Зейтинлике" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "villa", fiyat: 640000,
    sehir: "Girne", bolge: "Zeytinlik",
    oda: "4+1", banyo: 4, m2: 295, binaYasi: 5,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    
    ozellikler: ["Özel havuz", "Bahçe", "Şömine", "Jeneratör", "Deniz manzarası", "Kapalı otopark"],
    kapak: "/gorsel/ilan/ilan-02.webp",
    gorseller: ["/gorsel/ilan/ilan-02.webp", "/gorsel/ilan/ilan-13.webp"],
    emlakci: "deniz-tuncel",
    yayinTarihi: "2026-02-11", guncelleme: "2026-09-11",
    goruntulenme: 523,
    
    konum: { lat: 35.3245, lng: 33.2951 },
  },
  {
    id: 120, slug: "bafra-otel-konseptli-daire",
    baslik: { tr: "Bafra'da otel konseptli 1+1", en: "Hotel-concept 1+1 in Bafra", ru: "Квартира 1+1 в отельном комплексе в Бафре" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "daire", fiyat: 132000,
    sehir: "İskele", bolge: "Bafra",
    oda: "1+1", banyo: 1, m2: 62, binaYasi: 1,
    esyali: "esyali", tapu: "tmd", yabanciUygun: true,
    aidat: 75,
    ozellikler: ["Ortak havuz", "Denize sıfır", "Asansör", "Güvenlik kamerası", "Jeneratör"],
    kapak: "/gorsel/ilan/ilan-04.webp",
    gorseller: ["/gorsel/ilan/ilan-04.webp", "/gorsel/ilan/ilan-06.webp"],
    emlakci: "ayse-kurtulus",
    yayinTarihi: "2026-03-12", guncelleme: "2026-09-12",
    goruntulenme: 660,
    
    konum: { lat: 35.3489, lng: 34.0125 },
  },
  {
    id: 121, slug: "karaoglanoglu-kiralik-stüdyo",
    baslik: { tr: "Karaoğlanoğlu'nda kiralık stüdyo", en: "Studio to rent in Karaoğlanoğlu", ru: "Студия в аренду в Караогланоглу" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "kiralik", tip: "daire", fiyat: 480,
    sehir: "Girne", bolge: "Karaoğlanoğlu",
    oda: "1+0", banyo: 1, m2: 42, binaYasi: 10,
    esyali: "esyali", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 25,
    ozellikler: ["Otopark", "Balkon", "Deniz manzarası"],
    kapak: "/gorsel/ilan/ilan-11.webp",
    gorseller: ["/gorsel/ilan/ilan-11.webp", "/gorsel/ilan/ilan-10.webp"],
    emlakci: "mert-ozan",
    yayinTarihi: "2026-04-13", guncelleme: "2026-09-13",
    goruntulenme: 797,
    
    konum: { lat: 35.3371, lng: 33.2489 },
  },
  {
    id: 122, slug: "guzelyurt-narenciye-bahceli-ev",
    baslik: { tr: "Güzelyurt'ta narenciye bahçeli müstakil ev", en: "House with citrus grove in Güzelyurt", ru: "Дом с цитрусовым садом в Гюзельюрте" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "mustakil", fiyat: 235000,
    sehir: "Güzelyurt", bolge: "Güzelyurt Merkez",
    oda: "4+1", banyo: 2, m2: 190, binaYasi: 18,
    esyali: "esyasiz", tapu: "esdeger", yabanciUygun: false,
    
    ozellikler: ["Bahçe", "Su kuyusu", "Barbekü", "Doğa manzarası", "Otopark"],
    kapak: "/gorsel/ilan/ilan-22.webp",
    gorseller: ["/gorsel/ilan/ilan-22.webp", "/gorsel/ilan/ilan-21.webp"],
    emlakci: "yeliz-akinci",
    yayinTarihi: "2026-05-14", guncelleme: "2026-09-14",
    goruntulenme: 934,
    
    konum: { lat: 35.1978, lng: 32.9912 },
  },
  {
    id: 123, slug: "lefkosa-ortakoy-yeni-rezidans",
    baslik: { tr: "Lefkoşa Ortaköy'de yeni rezidans 3+1", en: "New 3+1 residence in Ortaköy, Nicosia", ru: "Новая резиденция 3+1 в Ортакёй" },
    aciklama: { tr: "Bölgenin en çok tercih edilen konumlarından birinde, bakımlı ve kullanıma hazır bir mülk. Marketlere, okullara, restoranlara ve sahile yürüme mesafesinde. Detaylı bilgi ve yerinde görüntüleme için danışmanımızla iletişime geçebilirsiniz.", en: "A well-maintained, move-in ready property in one of the area's most sought-after locations. Within walking distance of supermarkets, schools, restaurants and the shore. Contact our consultant for details and a viewing.", ru: "Ухоженная недвижимость, готовая к заселению, в одном из самых востребованных районов. В пешей доступности магазины, школы, рестораны и побережье. Свяжитесь с нашим консультантом для просмотра." },
    cevrilmis: true,
    islem: "satilik", tip: "rezidans", fiyat: 198000,
    sehir: "Lefkoşa", bolge: "Ortaköy",
    oda: "3+1", banyo: 2, m2: 130, binaYasi: 1,
    esyali: "esyasiz", tapu: "turk-kocani", yabanciUygun: true,
    aidat: 50,
    ozellikler: ["Asansör", "Kapalı otopark", "Jeneratör", "Güvenlik kamerası", "Balkon", "Şehir manzarası"],
    kapak: "/gorsel/ilan/ilan-05.webp",
    gorseller: ["/gorsel/ilan/ilan-05.webp", "/gorsel/ilan/ilan-12.webp"],
    emlakci: "kemal-arda",
    yayinTarihi: "2026-06-15", guncelleme: "2026-09-15",
    goruntulenme: 1071,
    
    konum: { lat: 35.1934, lng: 33.3406 },
  },
];
